### ISSUE TITLE
TypeError: _open() got an unexpected keyword argument 'threads'

### ISSUE THREAD

**Issue by dhwani2410** [nghiavtr/FuSeq_WES#3]
Hello,

I am trying to run the software using demo data, but it's showing an error.

python fuseq_wes.py --bam FuSeq_WES_testdata/test.bam --gtf UCSC_hg19_wes_contigSize3000_bigLen130000_r100/UCSC_hg19_wes_contigSize3000_bigLen130000_r100.json --outdir test_out/
Traceback (most recent call last):
  File "/nfs_master/dhwani/softwares/FuSeq_WES_v1.0.0/fuseq_wes.py", line 194, in <module>
    samfile = pysam.AlignmentFile(args.bam, "rb", threads=8)
  File "pysam/calignmentfile.pyx", line 340, in pysam.calignmentfile.AlignmentFile.__cinit__
  File "pysam/calignmentfile.pyx", line 378, in pysam.calignmentfile.AlignmentFile._open
TypeError: _open() got an unexpected keyword argument 'threads'

**Comment by nghiavtr** [comment]
Hi @dhwani2410,

Thank you for using FuSeq_WEs and I am sorry for the late reply. 

We have not seen this error before. However, it is likely you have not installed pysam yet. If so, please install that package (https://pysam.readthedocs.io/en/latest/installation.html) before running.

Best,
Nghia

**Comment by dhwani2410** [comment]
@nghiavtr 
i am able to run the code now. The error was with pysam code, as it did not allowed multiple threads
